#Benchmark Threads Configuration
aggregationAgents=2
editorialAgents=1
dataGeneratorWorkers=2

#Benchmark Configuration Parameters
warmupPeriodSeconds=5
benchmarkRunPeriodSeconds=30
datasetSize=100000
generatedTriplesPerFile=5000
queryTimeoutSeconds=300
querySubstitutionParameters=100000
benchmarkByQueryMixRuns=0
minUpdateRateThresholdOps=0.0
minUpdateRateThresholdReachTimePercent=0
maxUpdateRateThresholdOps=0.0
endpointURL=http://localhost:7200/repositories/benchmark
endpointUpdateURL=http://localhost:7200/repositories/benchmark/statements
endpointGraphStoreURL=http://localhost:7200/repositories/benchmark/statements
ontologiesPath=./data/ontologies
referenceDatasetsPath=./data/datasets
creativeWorksPath=./generated
queriesPath=./data/sparql
validationPath=./data/validation
definitionsPath=./definitions.properties
scriptsPath=./data/scripts
enableCompressionOnGeneratedData=false
creativeWorksInfo=dataset.info
generateCreativeWorksFormat=turtle
currentRateReportPeriodSeconds=0
saveDetailedQueryLogs=true
verbose=true

#Benchmark Operational Phases
loadOntologies=true
loadReferenceDatasets=true
generateCreativeWorks=true
loadCreativeWorks=true
generateQuerySubstitutionParameters=true
validateQueryResults=true
warmUp=true
runBenchmark=true
runBenchmarkOnlineReplicationAndBackup=false
checkConformance=false
